### ISSUE TITLE
Stuck in loop when connecting to new account

### ISSUE THREAD

**Issue by dg-concordium** [Concordium/eth-ccd-bridge#108] opened 2023-04-13 13:01 UTC
**Bug Description**

Using one Ethereum account (on Metamask) and one Concordium account, initiate a withdrawal.
In Metamask reject the withdrawal. Get stuck in the approval loop.
Try to get out of the approval loop by disconnecting all accounts and closing browser.
Reopen browser and open browser wallet and a different account. Connect to that account in bridge front end. Connect to same account in metamask.

**Expected Result**

Should get the transfer window.

**Actual Result**

Get the withdrawal approval screen.

**Versions**
- Software Version (0.1.1)
- OS (Windows 11)
- Browser (Chrome)
- Mobile device, if applicable

**Comment by soerenbf** [comment] 2023-04-14 06:45
This is a duplicate of #101 and is fixed in #109

**Closed by soerenbf** 2023-04-14 06:45 UTC
Labels: [Type] Bug
